// docs/src/examples/BasicKnob.vue
<template>
	<div>
		<SvgKnob v-model="value" />
		<span>{{ value.toFixed(2) }}</span>

		<SvgKnob v-model="value" :disabled="true" />
	</div>
</template>

<script>
import { ref } from 'vue';
import SvgKnob from '@eyewave/web-knobs/vue';

export default {
	components: { SvgKnob },
	setup() {
		const value = ref(0.0);
		return { value };
	}
};
</script>

<style scoped>
div {
	color: #22bfee;
}
</style>

// docs/src/examples/BasicKnob.tsx
import { useState } from 'react';
import { SvgKnob } from '@eyewave/web-knobs/react';

export default function () {
	const [value, setValue] = useState(0.0);

	return (
		<div style={{ color: '#22bfee' }}>
			<SvgKnob value={value} onValueChange={setValue} />
			<span>{value.toFixed(2)}</span>

			<SvgKnob value={value} disabled />
		</div>
	);
}
