// docs/src/examples/ParamKnob.tsx
import React, { useState } from 'react';
import { SvgKnob } from '@eyewave/web-knobs/react';
import { LinearParam, LogParam } from '@eyewave/web-knobs/core/params';

export default function () {
	const [value, setValue] = useState(0.0);

	const freqParam = new LogParam(20, 20_000, 10);
	const linParam = new LinearParam(0, 100);

	return (
		<section style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
			<div>
				<SvgKnob value={value} onValueChange={setValue} />
				<span>{Math.floor(freqParam.denormalize(value))}hz</span>
			</div>

			<div>
				<SvgKnob value={value} onValueChange={setValue} />
				<span>{Math.floor(linParam.denormalize(value))}%</span>
			</div>
		</section>
	);
}

// docs/src/examples/ParamKnob.vue
<template>
	<section>
		<div>
			<SvgKnob v-model="value" />
			<span>{{ Math.floor(freqParam.denormalize(value)) }} Hz</span>
		</div>

		<div>
			<SvgKnob v-model="value" />
			<span>{{ Math.floor(linParam.denormalize(value)) }}%</span>
		</div>
	</section>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { LinearParam, LogParam } from '@eyewave/web-knobs/core/params';
import { SvgKnob } from '@eyewave/web-knobs/vue';

const value = ref(0.0);

const freqParam = new LogParam(20, 20000, 10);
const linParam = new LinearParam(0, 100);
</script>

<style scoped>
section {
	display: flex;
	gap: 0.5rem;
	flex-wrap: wrap;
}
</style>
