// packages/svelte/src/lib/ImageKnob.svelte
<script lang="ts" module>
	import type { ImageKnobReactive } from '@web-knobs/core/components/image-knob';
	import type { DraggableReactive } from '@web-knobs/core/draggable';
	import type { HTMLAttributes } from 'svelte/elements';

	export type DraggableProps = DraggableReactive &
		ImageKnobReactive &
		HTMLAttributes<HTMLDivElement>;
</script>

<script lang="ts">
	import {
		DEFAULT_KNOB_SNAP_THRESHOLD,
		DEFAULT_KNOB_STEP,
		DEFAULT_KNOB_VALUE,
		DEFAULT_KNOB_WEIGHT
	} from '@web-knobs/core/draggable';

	import { createImageKnob, type ImageKnobApi } from '@web-knobs/core/components/image-knob';

	import { onDestroy, onMount } from 'svelte';

	let {
		value = $bindable(DEFAULT_KNOB_VALUE),
		disabled: isDisabled = false,
		defaultValue = DEFAULT_KNOB_VALUE,
		invertWheel = false,
		step = DEFAULT_KNOB_STEP,
		snapPoints,
		snapThreshold = DEFAULT_KNOB_SNAP_THRESHOLD,
		weight = DEFAULT_KNOB_WEIGHT,

		// Image Knob props
		src,
		numberOfFrames = null,
		width,
		height,

		...divProps
	}: DraggableProps = $props();

	let ref = $state<HTMLDivElement>();
	let engine = $state<ImageKnobApi | null>(null);

	onDestroy(() => engine?.destroy());
	onMount(() => {
		if (ref)
			engine = createImageKnob(ref, {
				src,
				width,
				height,

				onValueChange: (v) => (value = v),
				onDisabledChange: (v) => (isDisabled = v),
				onDefaultValueChange: (v) => (defaultValue = v),
				onInvertWheelChange: (v) => (invertWheel = v),
				onStepChange: (v) => (step = v),
				onSnapPointsChange: (v) => (snapPoints = v),
				onSnapThresholdChange: (v) => (snapThreshold = v),
				onWeightChange: (v) => (weight = v),

				onSrcChange: (v) => (src = v),
				onNumberOfFramesChange: (v) => (numberOfFrames = v),
				onWidthChange: (v) => (width = v),
				onHeightChange: (v) => (height = v)
			});

		$effect(() => engine?.setValue(value));
		$effect(() => engine?.setDisabled(isDisabled));
		$effect(() => engine?.setDefaultValue(defaultValue));
		$effect(() => engine?.setInvertWheel(invertWheel));
		$effect(() => engine?.setStep(step));
		$effect(() => snapPoints && engine?.setSnapPoints(snapPoints));
		$effect(() => engine?.setSnapThreshold(snapThreshold));
		$effect(() => engine?.setWeight(weight));

		$effect(() => engine?.setSrc(src));
		$effect(() => engine?.setNumberOfFrames(numberOfFrames));
		$effect(() => engine?.setWidth(width));
		$effect(() => engine?.setHeight(height));
	});
</script>

<div bind:this={ref} {...divProps} />

// packages/vue/src/ImageKnob.vue
<script setup lang="ts">
import {
	createImageKnob,
	type ImageKnobApi,
	type ImageKnobReactive
} from '@web-knobs/core/components/image-knob';
import {
	DEFAULT_KNOB_SNAP_THRESHOLD,
	DEFAULT_KNOB_STEP,
	DEFAULT_KNOB_VALUE,
	DEFAULT_KNOB_WEIGHT,
	type DraggableApi,
	type DraggableReactive
} from '@web-knobs/core/draggable';
import { ref, watch, onMounted, onUnmounted } from 'vue';

interface ImageKnobProps extends ImageKnobReactive, DraggableReactive {
	modelValue?: number;
}

const props = withDefaults(defineProps<ImageKnobProps>(), {
	modelValue: DEFAULT_KNOB_VALUE,
	disabled: false,
	defaultValue: DEFAULT_KNOB_VALUE,
	invertWheel: false,
	step: DEFAULT_KNOB_STEP,
	snapThreshold: DEFAULT_KNOB_SNAP_THRESHOLD,
	weight: DEFAULT_KNOB_WEIGHT,

	numberOfFrames: null
});

const emit = defineEmits<{
	'update:modelValue': [value: number];
	'update:disabled': [value: boolean];
	'update:defaultValue': [value: number];
	'update:invertWheel': [value: boolean];
	'update:step': [value: number];
	'update:snapPoints': [value: number[]];
	'update:snapThreshold': [value: number];
	'update:weight': [value: number];

	'update:src': [value: string];
	'update:numberOfFrames': [value: number | null];
	'update:width': [value: number];
	'update:height': [value: number];
}>();

const divRef = ref<HTMLDivElement>();
const engine = ref<ImageKnobApi | null>(null);

onMounted(() => {
	if (divRef.value) {
		engine.value = createImageKnob(divRef.value, {
			src: props.src,
			width: props.width,
			height: props.height,

			onValueChange: (v) => emit('update:modelValue', v),
			onDisabledChange: (v) => emit('update:disabled', v),
			onDefaultValueChange: (v) => emit('update:defaultValue', v),
			onInvertWheelChange: (v) => emit('update:invertWheel', v),
			onStepChange: (v) => emit('update:step', v),
			onSnapPointsChange: (v) => emit('update:snapPoints', v),
			onSnapThresholdChange: (v) => emit('update:snapThreshold', v),
			onWeightChange: (v) => emit('update:weight', v),

			onSrcChange: (v) => emit('update:src', v),
			onNumberOfFramesChange: (v) => emit('update:numberOfFrames', v),
			onWidthChange: (v) => emit('update:width', v),
			onHeightChange: (v) => emit('update:height', v)
		});
	}
});

onUnmounted(() => {
	engine.value?.destroy();
});

watch(
	() => props.modelValue,
	(v) => engine.value?.setValue?.(v)
);
watch(
	() => props.disabled,
	(v) => engine.value?.setDisabled?.(v)
);
watch(
	() => props.defaultValue,
	(v) => engine.value?.setDefaultValue?.(v)
);
watch(
	() => props.invertWheel,
	(v) => engine.value?.setInvertWheel?.(v)
);
watch(
	() => props.step,
	(v) => engine.value?.setStep?.(v)
);
watch(
	() => props.snapPoints,
	(v) => v && engine.value?.setSnapPoints?.(v)
);
watch(
	() => props.snapThreshold,
	(v) => engine.value?.setSnapThreshold?.(v)
);
watch(
	() => props.weight,
	(v) => engine.value?.setWeight?.(v)
);

watch(
	() => props.src,
	(v) => engine.value?.setSrc?.(v)
);
watch(
	() => props.numberOfFrames,
	(v) => engine.value?.setNumberOfFrames?.(v)
);
watch(
	() => props.width,
	(v) => engine.value?.setWidth?.(v)
);
watch(
	() => props.height,
	(v) => engine.value?.setHeight?.(v)
);
</script>

<template>
	<div ref="divRef">
		<slot />
	</div>
</template>
