// packages/react/src/Draggable.tsx
import {
	createDraggable,
	DEFAULT_KNOB_SNAP_THRESHOLD,
	DEFAULT_KNOB_STEP,
	DEFAULT_KNOB_VALUE,
	DEFAULT_KNOB_WEIGHT,
	type DraggableApi,
	type DraggableOptions,
	type DraggableReactive
} from '@web-knobs/core/draggable';

import { type ReactElement, useEffect, useRef } from 'react';

type Props = DraggableOptions & DraggableReactive & React.HTMLAttributes<HTMLDivElement>;

export default function Draggable({
	value = DEFAULT_KNOB_VALUE,
	disabled = false,
	defaultValue = DEFAULT_KNOB_VALUE,
	invertWheel = false,
	step = DEFAULT_KNOB_STEP,
	snapPoints,
	snapThreshold = DEFAULT_KNOB_SNAP_THRESHOLD,
	weight = DEFAULT_KNOB_WEIGHT,

	onValueChange,
	onDisabledChange,
	onDefaultValueChange,
	onInvertWheelChange,
	onStepChange,
	onSnapPointsChange,
	onSnapThresholdChange,
	onWeightChange,

	...divProps
}: Props): ReactElement {
	const containerRef = useRef<HTMLDivElement | null>(null);
	const engineRef = useRef<DraggableApi | null>(null);

	const callbacksRef = useRef<DraggableOptions | null>(null);

	useEffect(() => {
		callbacksRef.current = {
			onValueChange,
			onDisabledChange,
			onDefaultValueChange,
			onInvertWheelChange,
			onStepChange,
			onSnapPointsChange,
			onSnapThresholdChange,
			onWeightChange
		};
	}, [
		onValueChange,
		onDisabledChange,
		onDefaultValueChange,
		onInvertWheelChange,
		onStepChange,
		onSnapPointsChange,
		onSnapThresholdChange,
		onWeightChange
	]);

	useEffect(() => {
		if (!containerRef.current) return;

		if (engineRef.current) {
			engineRef.current.destroy();
			engineRef.current = null;
		}
		containerRef.current.innerHTML = '';

		engineRef.current = createDraggable(containerRef.current, {
			onValueChange: callbacksRef.current?.onValueChange,
			onDisabledChange: callbacksRef.current?.onDisabledChange,
			onDefaultValueChange: callbacksRef.current?.onDefaultValueChange,
			onInvertWheelChange: callbacksRef.current?.onInvertWheelChange,
			onStepChange: callbacksRef.current?.onStepChange,
			onSnapPointsChange: callbacksRef.current?.onSnapPointsChange,
			onSnapThresholdChange: callbacksRef.current?.onSnapThresholdChange,
			onWeightChange: callbacksRef.current?.onWeightChange
		});

		return () => {
			engineRef.current?.destroy();
			engineRef.current = null;
		};
	}, []);

	useEffect(() => engineRef.current?.setValue(value), [value]);
	useEffect(() => engineRef.current?.setDisabled(disabled), [disabled]);
	useEffect(() => engineRef.current?.setDefaultValue(defaultValue), [defaultValue]);
	useEffect(() => engineRef.current?.setInvertWheel(invertWheel), [invertWheel]);
	useEffect(() => engineRef.current?.setStep(step), [step]);
	useEffect(() => engineRef.current?.setSnapThreshold(snapThreshold), [snapThreshold]);
	useEffect(() => engineRef.current?.setWeight(weight), [weight]);

	useEffect(() => {
		if (snapPoints) {
			engineRef.current?.setSnapPoints(snapPoints);
		}
	}, [snapPoints]);

	return <div ref={containerRef} {...divProps} />;
}

// packages/svelte/src/lib/Draggable.svelte
<script lang="ts" module>
	import type { DraggableReactive } from '@web-knobs/core/draggable';
	import type { HTMLAttributes } from 'svelte/elements';

	export type DraggableProps = DraggableReactive & HTMLAttributes<HTMLDivElement>;
</script>

<script lang="ts">
	import {
		createDraggable,
		DEFAULT_KNOB_SNAP_THRESHOLD,
		DEFAULT_KNOB_STEP,
		DEFAULT_KNOB_VALUE,
		DEFAULT_KNOB_WEIGHT,
		type DraggableApi
	} from '@web-knobs/core/draggable';
	import { onDestroy, onMount } from 'svelte';

	let {
		children,
		value = $bindable(DEFAULT_KNOB_VALUE),
		disabled: isDisabled = false,
		defaultValue = DEFAULT_KNOB_VALUE,
		invertWheel = false,
		step = DEFAULT_KNOB_STEP,
		snapPoints,
		snapThreshold = DEFAULT_KNOB_SNAP_THRESHOLD,
		weight = DEFAULT_KNOB_WEIGHT,
		...divProps
	}: DraggableProps = $props();

	let ref = $state<HTMLDivElement>();
	let engine = $state<DraggableApi | null>(null);

	onDestroy(() => engine?.destroy());
	onMount(() => {
		if (ref)
			engine = createDraggable(ref, {
				onValueChange: (v) => (value = v),
				onDisabledChange: (v) => (isDisabled = v),
				onDefaultValueChange: (v) => (defaultValue = v),
				onInvertWheelChange: (v) => (invertWheel = v),
				onStepChange: (v) => (step = v),
				onSnapPointsChange: (v) => (snapPoints = v),
				onSnapThresholdChange: (v) => (snapThreshold = v),
				onWeightChange: (v) => (weight = v)
			});

		$effect(() => engine?.setValue(value));
		$effect(() => engine?.setDisabled(isDisabled));
		$effect(() => engine?.setDefaultValue(defaultValue));
		$effect(() => engine?.setInvertWheel(invertWheel));
		$effect(() => engine?.setStep(step));
		$effect(() => snapPoints && engine?.setSnapPoints(snapPoints));
		$effect(() => engine?.setSnapThreshold(snapThreshold));
		$effect(() => engine?.setWeight(weight));
	});
</script>

<div bind:this={ref} {...divProps}>{@render children?.()}</div>
