// packages/react/src/ImageKnob.tsx
import {
	createImageKnob,
	type ImageKnobApi,
	type ImageKnobOptions,
	type ImageKnobReactive
} from '@web-knobs/core/components/image-knob';

import {
	DEFAULT_KNOB_SNAP_THRESHOLD,
	DEFAULT_KNOB_STEP,
	DEFAULT_KNOB_VALUE,
	DEFAULT_KNOB_WEIGHT,
	type DraggableReactive
} from '@web-knobs/core/draggable';

import { type ReactElement, useEffect, useRef } from 'react';

type Props = ImageKnobOptions &
	DraggableReactive &
	ImageKnobReactive &
	React.HTMLAttributes<HTMLDivElement>;

export default function ImageKnob({
	value = DEFAULT_KNOB_VALUE,
	disabled = false,
	defaultValue = DEFAULT_KNOB_VALUE,
	invertWheel = false,
	step = DEFAULT_KNOB_STEP,
	snapPoints,
	snapThreshold = DEFAULT_KNOB_SNAP_THRESHOLD,
	weight = DEFAULT_KNOB_WEIGHT,

	src,
	numberOfFrames = null,
	width,
	height,

	onValueChange,
	onDisabledChange,
	onDefaultValueChange,
	onInvertWheelChange,
	onStepChange,
	onSnapPointsChange,
	onSnapThresholdChange,
	onWeightChange,

	onSrcChange,
	onNumberOfFramesChange,
	onWidthChange,
	onHeightChange,

	...divProps
}: Props): ReactElement {
	const containerRef = useRef<HTMLDivElement | null>(null);
	const engineRef = useRef<ImageKnobApi | null>(null);

	const callbacksRef = useRef<Omit<ImageKnobOptions, 'src' | 'width' | 'height'> | null>(null);

	useEffect(() => {
		callbacksRef.current = {
			onValueChange,
			onDisabledChange,
			onDefaultValueChange,
			onInvertWheelChange,
			onStepChange,
			onSnapPointsChange,
			onSnapThresholdChange,
			onWeightChange,
			onSrcChange,
			onNumberOfFramesChange,
			onWidthChange,
			onHeightChange
		};
	}, [
		onValueChange,
		onDisabledChange,
		onDefaultValueChange,
		onInvertWheelChange,
		onStepChange,
		onSnapPointsChange,
		onSnapThresholdChange,
		onWeightChange,
		onSrcChange,
		onNumberOfFramesChange,
		onWidthChange,
		onHeightChange
	]);

	/* 
  biome-ignore lint/correctness/useExhaustiveDependencies: src, width, height
    are getting updated in the engine somewhere else.
    This just needs to run once in the mount lifecycle
  */
	useEffect(() => {
		if (!containerRef.current) return;

		if (engineRef.current) {
			engineRef.current.destroy();
			engineRef.current = null;
		}
		containerRef.current.innerHTML = '';

		engineRef.current = createImageKnob(containerRef.current, {
			src,
			width,
			height,
			numberOfFrames,
			onValueChange: callbacksRef.current?.onValueChange,
			onDisabledChange: callbacksRef.current?.onDisabledChange,
			onDefaultValueChange: callbacksRef.current?.onDefaultValueChange,
			onInvertWheelChange: callbacksRef.current?.onInvertWheelChange,
			onStepChange: callbacksRef.current?.onStepChange,
			onSnapPointsChange: callbacksRef.current?.onSnapPointsChange,
			onSnapThresholdChange: callbacksRef.current?.onSnapThresholdChange,
			onWeightChange: callbacksRef.current?.onWeightChange,
			onSrcChange: callbacksRef.current?.onSrcChange,
			onNumberOfFramesChange: callbacksRef.current?.onNumberOfFramesChange,
			onWidthChange: callbacksRef.current?.onWidthChange,
			onHeightChange: callbacksRef.current?.onHeightChange
		});

		return () => {
			engineRef.current?.destroy();
			engineRef.current = null;
		};
	}, []);

	useEffect(() => engineRef.current?.setValue(value), [value]);
	useEffect(() => engineRef.current?.setDisabled(disabled), [disabled]);
	useEffect(() => engineRef.current?.setDefaultValue(defaultValue), [defaultValue]);
	useEffect(() => engineRef.current?.setInvertWheel(invertWheel), [invertWheel]);
	useEffect(() => engineRef.current?.setStep(step), [step]);
	useEffect(() => engineRef.current?.setSnapThreshold(snapThreshold), [snapThreshold]);
	useEffect(() => engineRef.current?.setWeight(weight), [weight]);

	useEffect(() => {
		if (snapPoints) {
			engineRef.current?.setSnapPoints(snapPoints);
		}
	}, [snapPoints]);

	return <div ref={containerRef} {...divProps} />;
}

// packages/svelte/src/lib/ImageKnob.svelte
<script lang="ts" module>
	import type { ImageKnobReactive } from '@web-knobs/core/components/image-knob';
	import type { DraggableReactive } from '@web-knobs/core/draggable';
	import type { HTMLAttributes } from 'svelte/elements';

	export type DraggableProps = DraggableReactive &
		ImageKnobReactive &
		HTMLAttributes<HTMLDivElement>;
</script>

<script lang="ts">
	import {
		DEFAULT_KNOB_SNAP_THRESHOLD,
		DEFAULT_KNOB_STEP,
		DEFAULT_KNOB_VALUE,
		DEFAULT_KNOB_WEIGHT
	} from '@web-knobs/core/draggable';

	import { createImageKnob, type ImageKnobApi } from '@web-knobs/core/components/image-knob';

	import { onDestroy, onMount } from 'svelte';

	let {
		value = $bindable(DEFAULT_KNOB_VALUE),
		disabled: isDisabled = false,
		defaultValue = DEFAULT_KNOB_VALUE,
		invertWheel = false,
		step = DEFAULT_KNOB_STEP,
		snapPoints,
		snapThreshold = DEFAULT_KNOB_SNAP_THRESHOLD,
		weight = DEFAULT_KNOB_WEIGHT,

		// Image Knob props
		src,
		numberOfFrames = null,
		width,
		height,

		...divProps
	}: DraggableProps = $props();

	let ref = $state<HTMLDivElement>();
	let engine = $state<ImageKnobApi | null>(null);

	onDestroy(() => engine?.destroy());
	onMount(() => {
		if (ref)
			engine = createImageKnob(ref, {
				src,
				width,
				height,

				onValueChange: (v) => (value = v),
				onDisabledChange: (v) => (isDisabled = v),
				onDefaultValueChange: (v) => (defaultValue = v),
				onInvertWheelChange: (v) => (invertWheel = v),
				onStepChange: (v) => (step = v),
				onSnapPointsChange: (v) => (snapPoints = v),
				onSnapThresholdChange: (v) => (snapThreshold = v),
				onWeightChange: (v) => (weight = v),

				onSrcChange: (v) => (src = v),
				onNumberOfFramesChange: (v) => (numberOfFrames = v),
				onWidthChange: (v) => (width = v),
				onHeightChange: (v) => (height = v)
			});

		$effect(() => engine?.setValue(value));
		$effect(() => engine?.setDisabled(isDisabled));
		$effect(() => engine?.setDefaultValue(defaultValue));
		$effect(() => engine?.setInvertWheel(invertWheel));
		$effect(() => engine?.setStep(step));
		$effect(() => snapPoints && engine?.setSnapPoints(snapPoints));
		$effect(() => engine?.setSnapThreshold(snapThreshold));
		$effect(() => engine?.setWeight(weight));

		$effect(() => engine?.setSrc(src));
		$effect(() => engine?.setNumberOfFrames(numberOfFrames));
		$effect(() => engine?.setWidth(width));
		$effect(() => engine?.setHeight(height));
	});
</script>

<div bind:this={ref} {...divProps} />
